### ISSUE TITLE
"Object 0 has no method 'call'"

### ISSUE THREAD

**Issue by rohan** [Anonyfox/meteor-scrape#22]
Hey! Just started using this package.

In `meteor shell`, I ran the following command:

`Scrape.feed("http://feeds.venturebeat.com/VentureBeat")`

which returned the following error message:

```
TypeError: Object 0 has no method 'call'
    at packages/digilord_sugarjs/packages/digilord_sugarjs.js:164:1
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at H.keys (packages/digilord_sugarjs/packages/digilord_sugarjs.js:164:1)
    at packages/digilord_sugarjs/packages/digilord_sugarjs.js:21:1
    at Array.map (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:448:1)
    at Array.<anonymous> (packages/digilord_sugarjs/packages/digilord_sugarjs.js:21:1)
    at /Users/rohan/.meteor/packages/babel-compiler/.5.8.24_1.1bn813n++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/babel-core/lib/traversal/scope/index.js:1131:132
    at Object.<anonymous> (/Users/rohan/.meteor/packages/babel-compiler/.5.8.24_1.1bn813n++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/babel-core/lib/traversal/scope/index.js:1145:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

What do? This is in a brand-new project.

**Comment by rohan** [comment]
Actually, it looks like just calling `Scrape` returns the same error.

**Comment by endotakashi1992** [comment]
Me too

**Comment by cyrilboh** [comment]
Me three. Actually running any command gives me the same error. Even console.log().

**Comment by alejandrocarlos** [comment]
I'm having this same issue. I have identified that it's an error with the sugarjs dependency. 

This is the full stack trace:
TypeError: Object 0 has no method 'call'
    at meteor://app/packages/digilord_sugarjs/packages/digilord_sugarjs.js:164:1
    at Array.forEach (meteor://app/packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at H.keys (meteor://app/packages/digilord_sugarjs/packages/digilord_sugarjs.js:164:1)
    at meteor://app/packages/digilord_sugarjs/packages/digilord_sugarjs.js:21:1
    at Array.map (meteor://app/packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:448:1)
    at Array.<anonymous> (meteor://app/packages/digilord_sugarjs/packages/digilord_sugarjs.js:21:1)
    at /Users/alejandrocarlos/.meteor/packages/babel-compiler/.5.8.24_1.ijudcs++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/babel-core/lib/traversal/scope/index.js:1131:132
    at Object.<anonymous> (/Users/alejandrocarlos/.meteor/packages/babel-compiler/.5.8.24_1.ijudcs++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/babel-core/lib/traversal/scope/index.js:1145:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by ethanteague** [comment]
Is there any way to use this package without this bug being resolved? This appears to be a show stopper.

**Comment by alexcbixly** [comment]
@ethanteague I'm not a developer on the project but it works fine unless you need the meteor shell. What I did was disable it when I need the shell and just enabled it when I need it to run. 

It's most likely going to be an old version of the digilord sugarjs package. An update to the dependencies might fix this.

**Comment by endotakashi1992** [comment]
This is may not be solution.I am using another package to scrape webpage,now.
https://github.com/endotakashi1992/meteor-metainspector
This is a wrapper for [node-metainspector](https://github.com/gabceb/node-metainspector).This package can use current meteor version.

If you are interesting,use it.

**Comment by sasikanth513** [comment]
any solutions for this issue?
